import type { Metadata } from 'next'
import './globals.scss'
import Header from '@/components/header/Header'
import Footer from '@/components/footer/Footer'
import Provider from '@/util/Providers'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
 
export default function RootLayout({
  children,
  
}: {
  children: React.ReactNode
}) {
  return (

    <html lang="ru">
      <body>
        <Header/>
        <Provider>{children}</Provider> 
        <Footer/>
        </body>
    </html>
  )
}